# Generated by Django 4.2.16 on 2024-10-07 18:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import project_supermarket.web.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[project_supermarket.web.validators.contains_only_letters_validator, django.core.validators.MinLengthValidator(2)])),
                ('speciality', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('category', models.CharField(blank=True, choices=[('salad', 'salad'), ('main', 'main'), ('desert', 'desert'), ('breakfast', 'breakfast')], max_length=9, null=True)),
                ('description', models.TextField(max_length=50)),
                ('picture', models.URLField()),
                ('cooker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.cooker')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), project_supermarket.web.validators.contains_only_letters_validator])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), project_supermarket.web.validators.contains_only_letters_validator])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('ingredients', models.JSONField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.product')),
                ('chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.cooker')),
            ],
        ),
    ]
