# Generated by Django 4.2.16 on 2024-11-15 18:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('offer_type', models.CharField(choices=[('percentage', 'percentage'), ('flat', 'flat discount')], max_length=10)),
                ('bundle_discount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cooker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cooker', to='web.cooker'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chef', to='web.cooker'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='product', serialize=False, to='web.product'),
        ),
        migrations.AddField(
            model_name='specialoffers',
            name='products',
            field=models.ManyToManyField(related_name='products_included', to='web.product'),
        ),
    ]
