# Generated by Django 4.2.16 on 2024-11-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffers',
            name='special_picture',
            field=models.URLField(default=1),
        ),
    ]
