# Generated by Django 4.2.16 on 2024-12-14 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_user_date_of_birth_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cooker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cooker', to='web.cooker'),
        ),
    ]
