# Generated by Django 4.2.16 on 2024-12-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_recipe_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe',
            field=models.TextField(max_length=500),
        ),
    ]
