# Generated by Django 4.2.16 on 2024-12-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_recipe_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='specialoffers',
            name='special_picture',
            field=models.URLField(),
        ),
    ]
