# Generated by Django 4.2.16 on 2024-12-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_product_cooker'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffers',
            name='products_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
